In [3]:
import numpy as np
list=[12.23, 13.32,100,36.32]
arr=np.array(list)
print(arr)
print(type(arr))


[ 12.23  13.32 100.    36.32]
<class 'numpy.ndarray'>



Create a 3*3 matrix



In [11]:
import numpy as np
arr = np.random.randint(2, 11, size=(3, 3))
print(arr)


[[ 3  4  2]
 [ 7  8  9]
 [ 8  5 10]]


create a null vector and update the value


In [16]:
import numpy as np
arr=np.zeros(10)
arr[6]=11
arr

array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

Reverse an array


In [21]:
arr=np.array([12,13,14 ,15 ,16 ,17, 18, 19 ,20 ,21, 22 ,23 ,24 ,25 ,26 ,27, 28 ,29, 30 ,31 ,32 ,33, 34 ,35 ,36 ,37])
arr[::-1]


array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])