In [8]:
import numpy as np
arr = np.zeros((5, 5))
arr[0, :] = 1        # top border
arr[-1, :] = 1       # bottom border
arr[:, 0] = 1        # left border
arr[:, -1] = 1       # right border
print(arr)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
import numpy as np
arr = np.ones((5, 5))
arr[0, :] = 0        # top border
arr[-1, :] = 0      # bottom border
arr[:, 0] = 0       # left border
arr[:, -1] = 0       # right border
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
