In [2]:
import numpy as np

# Create ratings for 100 employees and 4 quarters
ratings = np.random.randint(1, 6, (100, 4))

# Min-Max Normalization
min_val = ratings.min()
max_val = ratings.max()

normalized = (ratings - min_val) / (max_val - min_val)

#  Average rating per employee
employee_avg = ratings.mean(axis=1)

# Company average rating
company_avg = employee_avg.mean()

# Employees with above-average rating
above_avg_employees = np.where(employee_avg > company_avg)

# Output
print("Normalized ratings (first 3 employees):")
print(normalized[:3])

print("\nAverage rating per employee (first 3):")
print(employee_avg[:3])

print("\nCompany average rating:", company_avg)

print("\nEmployees above company average:")
print(above_avg_employees)


Normalized ratings (first 3 employees):
[[0.5  1.   1.   0.75]
 [1.   0.5  0.75 0.5 ]
 [0.75 0.75 0.25 0.5 ]]

Average rating per employee (first 3):
[4.25 3.75 3.25]

Company average rating: 3.0375

Employees above company average:
(array([ 0,  1,  2,  3, 10, 11, 12, 20, 21, 22, 24, 26, 28, 31, 33, 34, 36,
       38, 43, 46, 48, 50, 51, 52, 54, 56, 58, 62, 64, 66, 69, 72, 75, 77,
       78, 84, 85, 94, 95, 96, 97, 98]),)
