In [18]:
import numpy as np
list=[1,2,3,4,5,6,7,8]
arr=np.array(list)
tup=(1,2,3,4,5,6,7,8)
arr2=np.array(tup)
arr3=arr2.reshape(2,4)
print(arr)
print(arr3)



[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
