In [3]:
import numpy as np
temp_readings=np.random.randint(15,35, (7,24))
print(temp_readings)

[[16 17 17 34 30 23 21 24 22 26 28 16 33 28 26 28 23 19 21 23 17 19 21 27]
 [18 15 25 23 20 21 18 23 33 15 20 29 17 16 19 18 25 26 29 24 27 19 23 20]
 [32 26 29 30 34 31 31 33 23 26 27 32 20 16 31 22 20 32 21 27 33 31 29 29]
 [22 21 27 28 34 26 19 23 24 17 18 21 29 15 34 28 32 31 28 29 15 16 33 29]
 [24 29 23 32 22 19 27 16 17 32 28 28 22 34 29 19 21 30 24 18 34 20 17 15]
 [30 28 30 28 30 32 34 31 21 16 21 17 22 16 34 29 23 22 23 21 17 15 16 32]
 [22 29 25 16 15 34 28 23 23 17 32 25 22 28 27 28 24 34 30 33 20 32 31 21]]


In [4]:
Daily_max=temp_readings.max(axis=1)
Daily_min=temp_readings.min(axis=1)
print(Daily_max)
print(Daily_min)


[34 33 34 34 34 34 34]
[16 15 16 15 15 15 15]


In [6]:
# Step 3: Day with the largest temperature variation
daily_variation=Daily_max-Daily_min
largest_variation=np.argmax(daily_variation)
print(largest_variation)

3


In [7]:
# Step 4: Replace outliers beyond ±2 standard deviations with mean temperature
mean_temp = temp_readings.mean()
std_temp = temp_readings.std()

# Find outliers
outliers = (temp_readings > mean_temp + 2*std_temp) | (temp_readings < mean_temp - 2*std_temp)

# Replace outliers with mean
temp_readings[outliers] = mean_temp

print("\nTemperature array after replacing outliers:")
print(temp_readings)


Temperature array after replacing outliers:
[[16 17 17 34 30 23 21 24 22 26 28 16 33 28 26 28 23 19 21 23 17 19 21 27]
 [18 15 25 23 20 21 18 23 33 15 20 29 17 16 19 18 25 26 29 24 27 19 23 20]
 [32 26 29 30 34 31 31 33 23 26 27 32 20 16 31 22 20 32 21 27 33 31 29 29]
 [22 21 27 28 34 26 19 23 24 17 18 21 29 15 34 28 32 31 28 29 15 16 33 29]
 [24 29 23 32 22 19 27 16 17 32 28 28 22 34 29 19 21 30 24 18 34 20 17 15]
 [30 28 30 28 30 32 34 31 21 16 21 17 22 16 34 29 23 22 23 21 17 15 16 32]
 [22 29 25 16 15 34 28 23 23 17 32 25 22 28 27 28 24 34 30 33 20 32 31 21]]
